---

# *** LOGROTATE TASKS ***
- name: logrotate.conf file config 1
  replace:
    path: /etc/logrotate.conf
    regexp: '^rotate\s+(.*)$'
    replace: 'rotate 4'
- name: logrotate.conf file config 2
  replace:
    path: /etc/logrotate.conf
    regexp: '^#(.*)compress$'
    replace: 'compress'
# *** END LOGROTATE TASKS ***

# *** KDUMP TASKS ***
- name: Copy Kdump Config RHEL7
  copy: src=/etc/ansible/files/etc/kdump.conf.rhel7 dest=/etc/kdump.conf mode=0644
  when: ansible_distribution_major_version =='7'

- name: Copy Kdump Config RHEL6
  copy: src=/etc/ansible/files/etc/kdump.conf.rhel6 dest=/etc/kdump.conf mode=0644
  when: ansible_distribution_major_version =='6'

- name: sysconfig kdump config
  replace:
   path: /etc/sysconfig/kdump
   regexp: '^KDUMP_COMMANDLINE_REMOVE(.*)$'
   replace: 'KDUMP_COMMANDLINE_REMOVE="hugepages hugepagesz slub_debug kaslr fips=1"'
  when: ansible_distribution_major_version =='7'

- name: restart kdump RHEL6
  service: name=kdump state=restarted
  when: ansible_distribution_major_version =='6'

- name: restart kdump RHEL7
  systemd: name=kdump.service state=started enabled=yes
  when: ansible_distribution_major_version =='7'
# *** END KDUMP TASKS ***


