---

- name: "print name" 
  debug: msg="logrotate name -> {{ logrotate_name }}"

- name: "Copy Config | {{ logrotate_name }} " 
  template:
    src: etc/logrotate.d/template
    dest: "/etc/logrotate.d/{{ logrotate_name }}"
    owner: root
    group: "{{ logrotate_config_group }}"
    mode: 0644
  tags:
    - configuration
    - template-configuration
    - logrotate
