---
# for DMZ servers group_vars will override for eg: ansible_become_method: sudo
#- hosts: PHL-NONPRD:PHL-DMZNONPRD
- hosts: all
  # non centrify has no dzdo and i dont want retry files
  # become: true
  gather_facts: false
  
  tasks:
  - name: has sssd pkg
    command: rpm -q sssd-common 
    args:
     warn: no
    register: has_sssd
    #ignore_errors: true
    failed_when: "'not installed' in has_sssd.stdout_lines"
    changed_when: False

  - name: if not have sssd pkg do stuff 
    become: true
    replace:
     path: /etc/nsswitch.conf
     regexp: 'sss'
     replace: ""
    when: has_sssd.rc != 0

  - name: if not have sssd pkg do more stuff 
    become: true
    file:
     #path: /etc/sssd/sssd.conf
     path: /etc/sssd/ 
     state: absent 
    when: has_sssd.rc != 0
