---
# tasks file for user_create
- name: Create user
  user:
    name: '{{user_name}}'
    state: '{{user_state}}'
    remove: yes
    shell: /bin/bash
    groups: wheel
    append: yes
# different way to define user items:
  #user: name={{ item.name }} group={{ item.group }} shell={{ item.shell }} state='{{user_state}}'
  #with_items:
   #- { name: 'user1', group: 'group1', shell: '/bin/bash' }
   #- { name: 'daemon-user', group: 'group2', shell: '/sbin/nologin' }
  tags: 
      - user_stuff

- name: Publish local ssh public key for remote login
  authorized_key:
    user: '{{user_name}}'
    state: '{{user_state}}'
    # grabs from this control hosts, copies to remote authorized_keys file
    key: "{{ lookup('file', '{{ssh_key}}') }}"

- name: Add bashrc to include host and user
  template:
    dest: '~{{user_name}}/.bashrc'
    src: /etc/ansible/templates/bashrc.j2    
