---
- hosts: control
  vars:
    target: /tmp/scratch.txt
  
  tasks:
  - name: discover state
    command: grep 'is really an' {{target}}
    register: grep_state
    # runs if create or destroy is passed as a tag
    tags:
      - create
      - destroy
    ignore_errors: true

  - name: show the state of the file
    debug:
      var: grep_state.rc 

  - name: an idempotent command
    copy:
      src: /etc/ansible/files/scratch.txt
      dest: '{{target}}'
    when: grep_state.rc != 0
    tags:
      - create
      - destroy

  - name: another idempotent command
    lineinfile:
      dest: '{{target}}'
      regexp: '^(.*)is an(.*)$'
      backrefs: true
      line: '\1is really an\2'
    when: grep_state.rc != 0
    tags:
      - create
      - destroy

  - name: a non idempotent command
    shell: "echo this is a non-idempotent file >> /tmp/non-idempotent.txt"
    tags:
      - create

  - name: remove the file 
    file:
      path: /tmp/scratch.txt
      state: absent
    tags:
      - destroy

  - name: remove all files with string 
    shell: "rm -f  /tmp/*idempotent.txt" 
    args: 
      warn: false
    tags:
      - destroy

#  - name: make a backup file 
#    shell: cp /etc/sysctl.conf /etc/sysctl.conf_$(date +"%a-%b-%d-%Y_%H%M%S.ansible")

