---
- hosts: all
  become: true
  gather_facts: false

  tasks:
  - name: grep dir
    shell: "grep -ri pa21 /etc/auto*"
    no_log: true # less verbose output 
    register: wanted
    ignore_errors: yes # if fails will keep going and not produce retry file

  - name: if str exists
    #debug: msg="string exists"
    #when: wanted.rc == 0
    when: wanted.stdout.find('pa21') != -1 or wanted.stdout.find('PA21') != -1
    #debug: msg="string exists"
    # doesnt print line sep
    #debug: msg="{{ wanted.stdout }}"
    debug: msg="{{ wanted.stdout_lines }}"


