---
- hosts: phlprlxapnapp004
  become: true
  gather_facts: true

  # kmhpemcfspa21|KMHPEMCFSPA21

  tasks:
   - name: find in mount 
     command:  "mount -t nfs"
     register: wanted
   #- debug: msg="{{ wanted }}"
   - debug: msg="{{ wanted.stdout_lines }}"

#   - name: grep dir
#     shell: "grep -ri pa21 /etc/auto*"
#     no_log: true
#     register: wanted
#     ignore_errors: yes
#
   - name: do something  
     shell: "mount -t nfs | grep -c 10.0"
     register: outPut
     # enable ignore to get past this task if no output or command fails
     #ignore_errors: yes
   #- shell: echo "got enough do something"
   - debug: msg="got enough do something"
     when: outPut.stdout > "1"

  # - name: if str exists
#     #debug: msg="string exists"
#     #when: wanted.rc == 0
#     when: wanted.stdout.find('pa21') != -1 or wanted.stdout.find('PA21') != -1
#     #debug: msg="string exists"
#     # doesnt print line sep
#     #debug: msg="{{ wanted.stdout }}"
#     debug: msg="{{ wanted.stdout_lines }}"

   - name: check str exists
     shell: echo "found match"
     #when: "'10.0' in wanted.stdout"
     when: "'10.4'not in wanted.stdout"

   #- name: find  mount
   #  debug: msg="mounts  {{ inventory_hostname }} are {{ ansible_mounts }}"
   #  debug: msg="has it"
   #  debug: msg="{{ item.options }}"
   #  debug: var=item.options
   #  debug: msg="opts are {{ ansible_mounts[0].options }}"
   #  with_items: "{{ ansible_mounts }}"
   #  when: item.options | search ("10.0")
