---
# ** This is now called from site.yml -> database.yml **
# it will run the Oracle DB stuff (database.yml) only when the host is a member of the “ORACLE” hosts group: 
# e.g.:
# ansible-playbook site.yml --tags database -e "host_grp=all" --limit phldvlxsand001:phldvlxoras039:phldvlxoradt001
#
# we can still run this PB stand alone if needed
#
# for olistener run: ansible-playbook logrotate_ora.yml -e logrotate_name=olistener -e group=oinstall
# for ordbmsr run: ansible-playbook logrotate_ora.yml -e logrotate_name=ordms -e group=asmadmin
- hosts: '{{ server_name }}'
  become: true
  gather_facts: false
  vars:
    logrotate_name: '{{ name }}' # olistener or ordbms
    logrotate_config_group: root
    logrotate_log_paths:
       listen: "/u01/app/*/diag/tnslsnr/*/listener/trace/listener.log" # olistener
       alert:  "/u01/app/oracle/diag/rdbms/*/*/trace/alert_*.log" # ordbms
    logrotate_create_logs_with_mode: '0640'
    logrotate_create_logs_with_owner: oracle 
    logrotate_create_logs_with_group: '{{ group }}' # oinstall for listen;  asmadmin for ordbms
    logrotate_ignore_empty_logs: no
    logrotate_ignore_missing_logs: no
    logrotate_compression: yes
    logrotate_postpone_compression: no
    logrotate_frequency: weekly
    logrotate_retention_limit: 12
    logrotate_prerotate_command:  
    logrotate_postrotate_command: 
    logrotate_log_path: "{{ logrotate_log_paths['alert'] }}" # default to this

  tasks:
      #- debug: var=logrotate_log_paths['listen']
      #- debug: var=logrotate_name
      - name: "print name"
        debug: msg="logrotate name -> {{ logrotate_name }}"

      - name: "set vars based on rotate name"
        set_fact:
          logrotate_prerotate_command: runuser -l oracle -c "lsnrctl set Log_status off"
          logrotate_postrotate_command: runuser -l oracle -c "lsnrctl set Log_status on"
          logrotate_log_path: "{{ logrotate_log_paths['listen'] }}"
        when: logrotate_name == "olistener"

      #- debug: msg="path {{ logrotate_log_path }}"

      - name: "Copy Config"
        template:
            src: /etc/ansible/templates/logrotate-ora.j2
            dest: "/etc/logrotate.d/{{ logrotate_name }}"
            owner: root
            group: "{{ logrotate_config_group }}"
            mode: 0644


