---
#  ** This is called  from site.yml -> database.yml **
#
- hosts: '{{ server_name }}'
  become: yes
  gather_facts: true
  vars: 
    target: /tmp/oracle-snip.sh

  tasks:
    - name: oracle required pkgs
      yum: name={{item}} state=latest
      with_items:
        - compat-libcap1.x86_64 
        - compat-libstdc++-33.x86_64
        - libstdc++-devel.x86_64
        - gcc.x86_64
        - gcc-c++.x86_64
        - glibc-devel.x86_64 
        - libaio-devel.x86_64 

    - name: oracle preinstall rhel6 
      yum: name=local-oracle-rdbms-server-12cR1-preinstall.x86_64 state=latest
      when: ansible_distribution_major_version =='6'

    - name: oracle preinstall rhel7 
      yum: name=local-oracle-rdbms-server-12cR1-preinstall_el7.x86_64 state=latest
      when: ansible_distribution_major_version =='7'

    - name: copy oracle param script
      copy:
           src: /etc/ansible/files/oracle-snip.sh
           dest: '{{target}}'
           mode: 0755

    - name: run the sript   
      shell: /tmp/oracle-snip.sh >> /tmp/snip_log.txt

    - name: clean up 
      file: 
       path: '{{target}}'
       state: absent


# ansible-playbook -e "server_name=x"
