---
# http://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html
# CLI for async is: -B1 -P0
- hosts: sand
  become: true
  gather_facts: false
 
  tasks:
    - name: reboot  
      shell: sleep 2 && /sbin/shutdown -r now  
      async: 1
      poll: 0

