---
- hosts: linux_repo-all
  become: true

  # copy the template over
  tasks:
    - name: ensure nfs.service is running
      systemd: name=nfs.service state=started enabled=yes

    - name: copy template 
      copy:
            src: /etc/ansible/files/repo_exports 
            dest: /etc/exports
            owner: root
            group: root
            mode: 0644
      notify: 
            re_export_all

  # reload all exports
  handlers:
    - name: re_export_all
      command: 
            /usr/sbin/exportfs -ra
