---
#- hosts: localhost:phlprlxapnweb004
- hosts: localhost
  become: true
  gather_facts: false

  tasks:
  - name: grep dir
    #command: "grep -q rotate /etc/resolv.conf"
    command: "grep -q timeout /etc/resolv.conf"
    #no_log: true
    register: wanted
    #ignore_errors: yes

  #- name: do something if fail/succeed(set ignor error) 
    #command: /bin/something
  # debug: msg="it failed"
   # when: wanted is failed
   # when: wanted is succeeded
   
  #- name: check if defined  
    #shell: echo "see {{ wanted }} defined"
    #when: wanted is defined

  - name: if str exists
    #debug: msg="string exists"
    #when: wanted.rc == 0
    #when: wanted.stdout.find('pa21') != -1 or wanted.stdout.find('PA21') != -1
    #debug: msg="string exists"
    # doesnt print line sep
    # debug: msg="{{ wanted.stdout_lines }}"
    # shell: echo "wanted set!"
     debug: msg="wanted set"
     when: wanted
    
  #- name: no exist 
  #  debug: msg="wanted not set"
  #  when: not wanted


