---
- hosts: phldvlxsand001
  become: yes
  vars:
     inline_var: "line1"
     myList: [1,2,3]
  tasks:
    - name: check SEL
      command: /usr/sbin/getenforce
      register: sel_status
    #- debug: var=sel_status

    - command: /usr/sbin/setenforce Permissive
      when: sel_status.stdout != 'Permissive'

    - name: check FIPS
      command: /sbin/sysctl -n crypto.fips_enabled
      register: fips_status
    - debug: msg="{{ inventory_hostname }} FIPS DISABLED!!"
      when: fips_status.stdout != '1'

    - name: check syslog forward to SPLUNK
      stat:
        path: /etc/rsyslog.d/splunk.conf
      register: result
    - debug: msg="{{ inventory_hostname }} does NOT have syslog Splunk File!!"
      when: result.stat.exists == False 

    - debug: var=result.stat.checksum

    - name: check for TRM ACCOUNT
      command: id sch-trmscan
      register: trm_status 
      failed_when: "'FAILED' in trm_status.stderr"
    - debug: msg="{{ inventory_hostname }} does NOT have TRM ACCOUNT!!"
      when:  trm_status.rc == 1

    - name: Copy Issue File if Diff 
      copy: src=/etc/ansible/files/etc/issue dest=/etc/issue mode=0644
 
