---
 # This has moved to the Common ROLE called by site.yml
- hosts: rdgprlxjmp001
  become: yes
  gather_facts: true
  vars:
  tasks:
    - name: Copy Kdump Config RHEL7  
      copy: src=/etc/ansible/files/etc/kdump.conf.rhel7 dest=/etc/kdump.conf mode=0644
      when: ansible_distribution_major_version =='7'

    - name: Copy Kdump Config RHEL6  
      copy: src=/etc/ansible/files/etc/kdump.conf.rhel6 dest=/etc/kdump.conf mode=0644
      when: ansible_distribution_major_version =='6'

    - name: sysconfig kdump config
      replace:
       path: /etc/sysconfig/kdump
       regexp: '^KDUMP_COMMANDLINE_REMOVE(.*)$'
       replace: 'KDUMP_COMMANDLINE_REMOVE="hugepages hugepagesz slub_debug kaslr fips=1"'
      when: ansible_distribution_major_version =='7'

    - name: restart kdump RHEL6
      service: name=kdump state=restarted 
      when: ansible_distribution_major_version =='6'

    - name: restart kdump RHEL7
      systemd: name=kdump.service state=started enabled=yes
      when: ansible_distribution_major_version =='7'

