---
- hosts: RDG
  become: true

#  vars:
#    ntp_server: [phlntp1.kmhp.com, phlntp2.kmhp.com]

  # to disable: systemctl disable chronyd.service
  tasks:
    - name: remove chrony
      yum: name=chrony state=absent 

    - name: copy template 
      template: 
           src=/etc/ansible/templates/ntp.conf.j2 dest=/etc/ntp.conf 
           owner=root group=root mode=0644
           backup=yes
      notify: restart_ntp

    # rhel6 (need when clause or proper grouping )
  handlers:
    - name: restart_ntp
      service: name=ntpd state=restarted
